<?php

namespace AppBundle\Repository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{
		public function getList()
	{
		$query = $this->createQueryBuilder('p')
			->where("p.id > 1");

		$query->orderBy('p.position', 'ASC');

		return $query->getQuery()->getResult();
	}

	public function savePage($page)
	{
		$em = $this->getEntityManager();
		$em->persist($page);
		$em->flush();

		return 0;
	}
}
